server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 10.211.55.7:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"