server:
  port: 80
spring:
  application:
    name: cloud-consumer-feign-order


eureka:
  client:
    # 表示是否将自己注册进 EurekaServer 默认为 true,这里没必要入驻
    register-with-eureka: true
    # 是否从 EurekaServer 抓取已有的注册信息，默认为 true. 单节点无所谓，集群必须设置为 true，才能配置 ribbon 使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    prefer-ip-address: true #在访问地址显示ip地址
    instance-id: consumer-feign-order80

ribbon:
  #创建连接最大时间
  ReadTimeout: 5000
  #接受数据最大时间
  ConnectTimeout: 5000
